// Fake <bits/stdc++.h> for macOS/Clang
#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <set>
#include <map>
#include <queue>
#include <stack>
#include <list>
#include <deque>
#include <cmath>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <iterator>
#include <sstream>
#include <fstream>
#include <bitset>
#include <unordered_map>
#include <unordered_set>
#include <tuple>
#include <climits>
#include <cfloat>
#include <cassert>
#include <cstring>
#include <cctype>
#include <cstdlib>
#include <ctime>
